### ISSUE TITLE
Model building work [ParkingArea]

### ISSUE THREAD

**Issue by qoopen0815** [Field-Robotics-Japan/vtc_world_blender#2]
from PR https://github.com/Field-Robotics-Japan/vtc_world_blender/pull/1

I'm building ParkingArea in calm0815/modify_ParkingArea branch.
The working list about my task.

- [x] Polygon reduction
- [x] Separate driveways and sidewalks
- [ ] Planting of trees 
- [x] Transcription of road signs

**Comment by RyodoTanaka** [comment]
Planting trees will be work on Unity.  And it is not necessary for blender.
Thus I assume the Planting of trees task should be ignored on this issue.
I will close this issue.
